### ISSUE TITLE
bibliography - add instructions for non-zotero users

### ISSUE THREAD

**Issue by twhiteaker** [lter/im-manual#10]
i.e., send a file.

what format?

that means that we do a mass replacement, not an incremental update.  That puts the burden of eliminating duplicates (lots of them) on the LNO.

**Comment by marty-downs** [comment]
Added bibtex instructions, as well as details on what to include (and not include) and a link to page with details about item types and required fields.

**Comment by twhiteaker** [comment]
Didn't we co-author a zotero best practices document?  Whatever happened to that, and is it pertinent to this page?

**Comment by twhiteaker** [comment]
Fixed in https://github.com/lter/im-manual/commit/4c2fa2f113eb7615a49148355c7aa926006e9e02. I added a bullet about including the DOI.
