### ISSUE TITLE
edits to site-personnel instructions

### ISSUE THREAD

**Issue by twhiteaker** [lter/im-manual#3]
The site-personnel page states that Row 1 lists the common-language descriptions of each field.  However, it actually starts on row 2.

Can the name fields accept hyphenated names? What about other special characters?  What about things like apostrophes vs the fancy apostrophe Word uses (straight quotes vs smart quotes)?

Are initials allowed (most commonly used for middle names)? If so, Should a period follow the initial?

The Active User column does not appear to contain logins as indicated in the documentation, but rather a boolean value, e.g., TRUE.

What are columns S through AC?

Is Primary (Affiliation) just for that LTER site or across all LTER sites?

In the spreadsheet, should Contact-Site ID be renamed to Site-Contact ID to match the documentation? Also, that is the only column name not in bold.

If adding a new participant with two roles, are both rows adjacent or does the second role go in the "adding roles" section after the blank row.

**Comment by twhiteaker** [comment]
If I want to make edits to an existing contact, do I create a case or edit the spreadsheet? This is for a single update and not what I would consider a bulk update.

If done via create a case, I suggest changing the Case Reason dropdown option from New Participant to **Personnel Update**.  I think that dropdown change should happen anyway, so that it also supports the "bulk edit" use case.

**Comment by twhiteaker** [comment]
Perhaps explain that Google sheet updates are automatically saved as soon as they are made?

**Comment by marty-downs** [comment]
I think these have now all been addressed. On to Renée's comments...

**Comment by twhiteaker** [comment]
All items were addressed except these:

* In the hub, when submitting a [support case](https://lternetwork.force.com/lterhub/s/contactsupport), replace New Participant with Personnel Update. This is a change to the Hub, not this repo.
* In the Rows section on the personnel page, Row 3 lists the SalesForce names for each field, and Row 2 lists the common-language descriptions of each field.

**Comment by marty-downs** [comment]
I believe these are both now addressed as well. Thanks.
