### ISSUE TITLE
Flesh out website section with links

### ISSUE THREAD

**Issue by marty-downs** [lter/im-manual#6]
Biblio, personnel, etc.

**Comment by twhiteaker** [comment]
I worry about stale links, and too many links.  When example sites are listed, I think it would be better to link to the home page for each site.

**Comment by twhiteaker** [comment]
If our readers can't find biblio or personnel links on the example sites, then those sites aren't good examples.

**Comment by twhiteaker** [comment]
Added site home page links in ee61f1c809e81e325aae273ef74a3fef9f7fd6aa
